blogging_web/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
    path('profile/', include('users.urls')),
    path('subscribe/', include('newsletter.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from .views import newsletter_subscribe, newsletter_unsubscribe, send_newsletter


app_name = 'newsletter'
urlpatterns = [
    path('newsletter-subscribe/', newsletter_subscribe, name='subscribe'),
    path('newsletter-unsubscribe/', newsletter_unsubscribe, name='unsubscribe'),
    path('newsletter-subscribe-send/',
         send_newsletter, name='send_newsletter'),
]

users/urls.py
from django.urls import path
from . import views as users_view
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path('register/', users_view.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', users_view.profile, name='profile'),
    path('update_profile/', users_view.UpdateProfile, name='update-profile'),

    # change password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change.html'), name='password_change'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done')
]

newsletter/models.py
from django.db import models

# Create your models here.


class NewsLetterUserList(models.Model):
    email = models.EmailField(max_length=254)
    subscription_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class SendEmailToNewsLetterUser(models.Model):
    EMAIL_STATUS_CHOICES = (
        ("Draft", "Draft"),
        ("Published", "Published")
    )
    subject = models.CharField(max_length=250)
    body = models.TextField()
    status = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

newsletter/forms.py
from django import forms
from .models import NewsLetterUserList, SendEmailToNewsLetterUser
from tinymce import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class NewsLetterUserListForm(forms.ModelForm):
    class Meta:
        model = NewsLetterUserList
        fields = ['email']

    # notice clean_email is nested within Meta Class
"""     def clean_email(self):
        email = self.cleaned_data.get('email')
        return email """


class SendEmailToNewsLetterUserForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCEWidget(
        attrs={'required': False, 'cols': 10, 'rows': 10})
    )

    class Meta:
        model = SendEmailToNewsLetterUser
        fields = ['subject', 'body', 'status']

newsletter/views.py
from django.shortcuts import render, redirect
from .models import NewsLetterUserList, SendEmailToNewsLetterUser
from .forms import NewsLetterUserListForm, SendEmailToNewsLetterUserForm
from django.contrib import messages
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
from django.template.loader import get_template
from django.utils.safestring import mark_safe


def newsletter_subscribe(request):
    if request.method == 'POST':
        form = NewsLetterUserListForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if NewsLetterUserList.objects.filter(email=instance.email).exists():
                messages.success(request, 'This email is already registered!')
            else:
                instance.save()
                subject, recipient_list = 'Subscribed Successfully', [
                    instance.email]
                from_email = settings.EMAIL_HOST_USER
                with open(settings.BASE_DIR + "\\newsletter\\templates\\newsletter\\email_txt.txt") as f:
                    body = f.read()
                message = EmailMultiAlternatives(
                    subject=subject, body=body, from_email=from_email, to=recipient_list)
                temp = get_template('newsletter/email.html').render()
                message.attach_alternative(temp, 'text/html')
                message.send()
                messages.success(
                    request, 'You successfully subscribed to our newsletter, please check your email')
                return redirect('blog-home')
    else:
        form = NewsLetterUserListForm()
    return render(request, 'blogApp/home.html', {'subscribe_form': form})


def newsletter_unsubscribe(request):
    form = NewsLetterUserListForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsLetterUserList.objects.filter(email=instance.email).exists():
            NewsLetterUserList.objects.filter(email=instance.email).delete()
            messages.success(
                request, 'We\'re sad to see you go :(')
            return redirect('blog-home')
        else:
            messages.success(request, 'Email doesn\'t exists!')

    return render(request, 'newsletter/unsubscribe.html', {'unsubscribe_form': form})


def send_newsletter(request):
    form = SendEmailToNewsLetterUserForm(request.POST or None)
    if form.is_valid():
        instance = form.save()

        if instance.status == 'Published':
            subject = instance.subject
            body = instance.body
            from_email = settings.EMAIL_HOST_USER

            for newsletter_obj in NewsLetterUserList.objects.all():
                msg = EmailMultiAlternatives(
                    subject, body, from_email, [newsletter_obj.email])
                msg.attach_alternative(body, "text/html")
                msg.send()

    return render(request, 'newsletter/send-email.html', {'form': form})

newsletter/templates/newsletter/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
    h1 {
        color: blue;
    }
    
    </style>
</head>
<body>
    <h1>Welcome to our website</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatem voluptate voluptatibus sequi odit. Fuga, laboriosam libero eaque repellat natus modi reiciendis velit maxime omnis voluptatum inventore, placeat debitis voluptates eveniet?</p>
    <small>Click here to <a href="{% url 'newsletter:unsubscribe' %}">unsubscribe</a></small>
</body>
</html>

newsletter/templates/newsletter/send-email.html
{% extends 'blogApp/base.html' %}
{% load crispy_forms_tags %}


{% block main %}
    <div class="content-section">
        <form action="." method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Send NewsLetter" class='btn btn-primary'>
        </form>
    </div>
{% endblock main %}

newsletter/templates/newsletter/unsubscribe.html
{% extends 'blogApp/base.html' %} 
{% load crispy_forms_tags %} 

{% block main %}

<div class="content-section">
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Unsubscribe</legend>
    <form action="#" method="POST">
      {% csrf_token %} 
      {{ unsubscribe_form|crispy }}
      <input type="submit" class="btn btn-outline-success" value="Unsubscribe" />
    </form>
  </fieldset>
</div>

{% endblock main %}