blogging_web/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
    path('profile/', include('users.urls')),
    path('subscribe/', include('newsletter.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views as users_view
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path('register/', users_view.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', users_view.profile, name='profile'),
    path('update_profile/', users_view.UpdateProfile, name='update-profile'),

    # change password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change.html'), name='password_change'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username}\'s Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.width > 300 or img.height > 300:
            img.thumbnail((300, 300))
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class RegisterForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from users.forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm, RegisterForm
from django.contrib.auth.models import User

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Account created successfuly, log in as {username}')
            return redirect('users:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def UpdateProfile(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST, instance=request.user)
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if register_form.is_valid() and profile_form.is_valid():
            register_form.save()
            profile_form.save()
            messages.success(request, 'Profile has been updated successfully!')
            return redirect('users:profile')
    else:
        register_form = RegisterForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    context = {
        'register_form': register_form,
        'profile_form': profile_form
    }

    return render(request, 'users/edit_profile.html', context)

users/templates/users/edit_profile.html
{% extends 'blogApp/base.html' %} {% load crispy_forms_tags %} {% block main %}
<div class="content-section">
  <div class="media">
    <form action="." method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ register_form|crispy }} {{ profile_form|crispy }}
      <button class="btn btn-outline-success">Update</button>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'blogApp/base.html' %} {% load crispy_forms_tags %} {% block main %}

<div class="content-section">
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Log In</legend>
    <form action="#" method="POST">
      {% csrf_token %} {{ form|crispy }}
      <input type="submit" class="btn btn-outline-success" value="Log In" />
    </form>
    <div class="form-group border-top mt-4">
      <small class="text-muted"
        >Create a new account? <a href="{% url 'users:signup' %}">Sign up</a>
        <br />
        <a href="{% url 'password_reset' %}">Reset password</a>
      </small>
      <br />
    </div>
  </fieldset>
</div>

{% endblock main %}

users/templates/users/logout.html
{% extends 'blogApp/base.html' %} {% block main %} {% load crispy_forms_tags %}
<div class="content-section">
  <h3 class="border-bottom mb-2 pb-3">Successfully logged out</h3>
  <a href="{% url 'users:login' %}">Login Again</a>
</div>

{% endblock main %}

users/templates/users/password_change.html
{% extends 'blogApp/base.html' %} {% load crispy_forms_tags %} {% block main %}
<div class="content-section">
  <h2 class="border-bottom pb-2 mb-3">Change Password</h2>
  <form action="." method="POST">
    {% csrf_token %} {{form|crispy}}
    <input type="submit" class="btn btn-outline-info" value="Change password" />
    <a href="{% url 'users:profile' %}" class="btn btn-outline-secondary"
      >Cancel</a
    >
  </form>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'blogApp/base.html' %} {% block main %}
<div class="alert alert-info">
  Your password has been changed successfully!
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'blogApp/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="content-section">
        <h2 class="border-bottom pb-2 mb-3">Request password reset</h2>
        <form action="." method='POST'>
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class='btn btn-info' value='Request password Reset'>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'blogApp/base.html' %}

{% block main %}
    <div class="alert alert-info border-bottom pb-2 mb-3">
        You have successfully reset your password!
    </div>
    <a href="{% url 'users:login' %}">Log In </a>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'blogApp/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="content-section">
        <h2 class="border-bottom pb-2 mb-3">Reset Password</h2>
        <form action="." method='POST'>
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class='btn btn-info' value='Reset Password'>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'blogApp/base.html' %}

{% block main %}
    <div class="alert alert-info">
        An email has been sent to your account, follow the instructions to reset your password.
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'blogApp/base.html' %} {% block main %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{user.profile.image.url}}" />
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
      <a href="{% url 'users:update-profile' %}" class="btn btn-sm btn-outline-danger"
        >Settings</a
      >
      <a
        href="{% url 'users:password_change' %}"
        class="btn btn-sm btn-outline-danger"
        >Change Password</a
      >
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'blogApp/base.html' %} {% block main %} {% load crispy_forms_tags %}
<div class="content-section">
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Create an account!</legend>
    <form action="#" method="POST">
      {% csrf_token %} {{ form|crispy }}
      <input type="submit" class="btn btn-outline-success" />
    </form>
    <div class="form-group border-top mt-4">
      <small class="text-muted"
        >Already have an account <a href="{% url 'users:login' %}">Log in</a>
      </small>
    </div>
  </fieldset>
</div>

{% endblock main %}