blogApp/urls.py
from django.urls import path, include
from . import views as blog_view
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', blog_view.PostListView.as_view(), name='blog-home'),
    path('posts/<str:username>/',
         blog_view.UserPostsView.as_view(), name='users-posts'),

    path('new_post/', blog_view.PostCreateView.as_view(), name='blog-create'),

    path('post/<slug:title_slug>/update/',
         blog_view.PostUpdateView.as_view(), name='blog-update'),

    path('post/<slug:title_slug>/delete/',
         blog_view.PostDeleteView.as_view(), name='blog-delete'),

    path('post/<slug:title_slug>/', blog_view.post_detail, name='blog-detail'),
    path('about/', blog_view.about, name='blog-about'),
    path('tinymce/', include('tinymce.urls')),
    path('search-blogs/', blog_view.SearchBlog.as_view(), name='search_blogs'),

    # password reset
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

blogging_web/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
    path('profile/', include('users.urls')),
    path('subscribe/', include('newsletter.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from .views import newsletter_subscribe, newsletter_unsubscribe, send_newsletter


app_name = 'newsletter'
urlpatterns = [
    path('newsletter-subscribe/', newsletter_subscribe, name='subscribe'),
    path('newsletter-unsubscribe/', newsletter_unsubscribe, name='unsubscribe'),
    path('newsletter-subscribe-send/',
         send_newsletter, name='send_newsletter'),
]

users/urls.py
from django.urls import path
from . import views as users_view
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path('register/', users_view.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', users_view.profile, name='profile'),
    path('update_profile/', users_view.UpdateProfile, name='update-profile'),

    # change password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change.html'), name='password_change'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done')
]

blogApp/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from PIL import Image


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField(
        default='default.jpg', upload_to='posts/%Y/%m/%d')
    view_counts = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'title_slug': self.slug})

    def get_update_url(self):
        return reverse('blog-update', kwargs={'title_slug': self.slug})

    def get_delete_url(self):
        return reverse('blog-delete', kwargs={'title_slug': self.slug})


""" def save(self, *args, **kwargs):
        img = Image.open(self.thumbnail.path) """

blogApp/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(widget=TinyMCEWidget(
        attrs={'required': False, 'cols': 10, 'rows': 10})
    )
    thumbnail = forms.ImageField()

    class Meta:
        model = Post
        fields = ['title', 'content', 'thumbnail']

blogApp/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.db.models import F
from .forms import PostForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic import View
from newsletter.forms import NewsLetterUserListForm


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blogApp/home.html'
    ordering = '-created_at'
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        context['subscribe_form'] = NewsLetterUserListForm()
        return context


def post_detail(request, title_slug):
    obj = get_object_or_404(Post, slug=title_slug)
    session_key = f'user_{title_slug}'

    if not request.session.get(session_key, False):
        type(obj).objects.filter(pk=obj.pk).update(
            view_counts=F('view_counts') + 1
        )
        request.session[session_key] = True

    return render(request, 'blogApp/detail.html', {'post': obj})


""" class PostDetailView(DetailView):
    model = Post
    template_name = 'blogApp/detail.html' """


class PostUpdateView(SuccessMessageMixin, UpdateView, LoginRequiredMixin, UserPassesTestMixin):
    model = Post
    form_class = PostForm
    template_name = 'blogApp/update.html'
    success_url = '/'
    success_message = "<strong>%(title)s</strong> updated successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False

    def get_object(self):
        slug = self.kwargs.get('title_slug')
        return get_object_or_404(Post, slug=slug)


class PostDeleteView(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = 'blogApp/delete.html'
    success_message = 'Post Deleted'

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False

    def get_object(self):
        slug = self.kwargs.get('title_slug')
        return get_object_or_404(Post, slug=slug)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blogApp/create.html'
    success_url = '/'
    success_message = "<strong>%(title)s</strong> created successfully!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UserPostsView(ListView):
    # model = Post
    queryset = Post.objects.all()
    template_name = 'blogApp/users_posts.html'
    paginate_by = 3
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(author=get_object_or_404(User, username=self.kwargs.get('username'))).order_by('-date_created')


@login_required
def about(request):
    context = {
        'title': 'about'
    }
    return render(request, 'blogApp/about.html', context)


class SearchBlog(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('query')
        if query:
            queryset = Post.objects.filter(
                Q(title__icontains=query) |
                Q(title__icontains=query)
            ).distinct()

        context = {
            'queryset': queryset,
            'query': query
        }

        return render(request, 'blogApp/search_results.html', context)

blogApp/templates/blogApp/about.html
{% extends 'blogApp/base.html' %} {% load static %} {% block main %}
<h2>About page!</h2>
<p>
  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam molestiae
  ducimus dolorum possimus iure provident tenetur alias unde in reiciendis id,
  accusantium nisi vero voluptates sint earum totam cupiditate nihil?
</p>
<img
  width="70%"
  style="border-radius:1rem;"
  src="{% static 'blogApp/imgs/author.jpg' %}"
/>
<br />
<br />
<br />
{% endblock main %}

blogApp/templates/blogApp/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    {{ form.media }}
    <link rel="stylesheet" href='{% static "blogApp/main.css" %}'>

    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Django-blog</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Django Blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
              <a class="nav-item nav-link" href="{% url 'blog-create' %}">Create</a>
              {% if user.username == 'Admin' %}
                  <a class="nav-item nav-link" href="{% url 'newsletter:send_newsletter' %}">Send Newsletter</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'users:profile' %}"> 
                <i class="fas fa-user"></i> Profile</a>
              <a class="nav-item nav-link" href="{% url 'users:logout' %}">Log Out</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'users:login' %}">Log In</a>
              <a class="nav-item nav-link" href="{% url 'users:signup' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
              {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                  {{message|safe}}
                </div>
                {% endfor %}
              {% endif %}

              {% block main %}
              
              {% endblock %}
            </div>

            <div class="col-md-4">
              <div class="content-section">
                <h1 class="border-bottom pb-3 mb-3">Search blogs:</h1>
                <form action="{% url 'search_blogs' %}">
                  {% csrf_token %}
                  <input type="text" name="query" class="form-control mb-3" placeholder="Search Blogs by Title ...">
                  <button type="Submit" class="btn btn-primary btn-block">Search</button>
                </form>
              </div>

              <div class="content-section">
                <h2 class="border-bottom pb-3 mb-3">Daily Newsletter?</h2>
                <form action="{% url 'newsletter:subscribe' %}" method="POST">
                  {% csrf_token %} 
                  {{ subscribe_form|crispy }}
                  <button type="Submit" class="btn btn-primary btn-block">Subscribe</button> <br>
                </form>
              </div>
              <div class="content-section">
                  <h3>Our Sidebar</h3>
                  <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                      <li class="list-group-item list-group-item-light">Latest Posts</li>
                      <li class="list-group-item list-group-item-light">Announcements</li>
                      <li class="list-group-item list-group-item-light">Calendars</li>
                      <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                  </p>
              </div>
            </div>
        </div>
    </main>

    <script src="https://kit.fontawesome.com/987eff0098.js" crossorigin="anonymous"></script>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

blogApp/templates/blogApp/create.html
{% extends 'blogApp/base.html' %} {% load crispy_forms_tags %} {% block main %}

<div class="content-section">
  <h2 class="border-bottom pb-3 mb-3 text-success">Create New Post</h2>
  <form action="." method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form|crispy}}
    <button class="btn btn-success">Create</button>
  </form>
</div>

{% endblock %}

blogApp/templates/blogApp/delete.html
{% extends 'blogApp/base.html' %} {% block main %}

<div class="content-section">
  <h2 class="border-bottom pb-3 mb-3 text-danger">
    <small>Delete "{{ object.title }}"</small>
  </h2>
  <form action="." method="POST">
    {% csrf_token %} Are you sure you want to delete? <br />
    <input type="submit" class="btn btn-danger btn-sm my-2" value="Delete" />
    <a href="{% url 'blog-home' %}" class="btn btn-secondary my-2 btn-sm "
      >Cancel</a
    >
  </form>
</div>

{% endblock %}

blogApp/templates/blogApp/detail.html
{% extends 'blogApp/base.html' %} {% load humanize %} {% block main %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata my-3">
      <img
        src="{{ post.author.profile.image.url }}"
        class="article-svg rounded-circle mr-2"
        alt=""
      />
      {{ post.author }}
      <small class="text-muted mb-2">
        {% if post.updated_at == post.created_at %}
        <i class="fa fa-plus" aria-hidden="true"></i> Posted
        {{post.created_at|timesince }} ago {% else %}
        <i class="fas fa-edit mx-1"></i> Updated {{ post.updated_at|timesince }}
        ago {% endif %} <i class="fas fa-eye"></i> {{ post.view_counts }}
      </small>
      <br />
      {% if request.user == post.author %}
      <a href="{{ post.get_delete_url }}" class="my-1 btn btn-danger btn-sm"
        >Delete</a
      >
      <a href="{{post.get_update_url}}" class="my-1 btn btn-warning btn-sm"
        >Update</a
      >
      {% endif %}
    </div>
    <img src="{{ post.thumbnail.url }}" width="100%" alt="" />
    <h2 class="my-2">{{ post.title }}</h2>
    <p class="article-content">{{ post.content|safe }}</p>
  </div>
</article>
{% endblock main %}




  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a href="?page=1" class='btn btn-outline-info'>1</a>
      <a href="?page={{page_obj.previous_page_number}}" class='btn btn-outline-info'>Previous</a>
    {% endif %}

    {% for num_page in page_obj.paginator.page_range %}
      {% if num_page == page_obj.number %}
        <a href="?page{{num_page}}" class='btn btn-info'>{{num_page}}</a>

      {% elif num_page > page_obj.number|add:'-3' and num_page < page_obj.number|add:'3' %}
        <a href="?page={{ num_page }}" class='btn btn-outline-info'>{{num_page}}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class='btn btn-outline-info'>Next</a>
      <a href='?page={{ page_obj.paginator.num_pages }}' class='btn btn-outline-info'>Last</a>
    {% endif %}
  {% endif %}

blogApp/templates/blogApp/home.html
{% extends 'blogApp/base.html' %} 
{% block main %} 
  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <img class='article-svg rounded-circle mr-2' src="{{ post.author.profile.image.url }}" alt="">
          <a class="mr-2" href="{% url 'users-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">
            {% if post.updated_at == post.created_at %}
            <i class="fas fa-plus-square"></i> Posted {{ post.created_at|timesince }} ago
            {% else %} 
              <i class="fas fa-edit mx-1"></i> Updated {{ post.updated_at|timesince }} ago
            {% endif %}           
            <i class="fas fa-eye"></i> {{ post.view_counts }}
          </small>
        </div>
        <h2><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <div class="row">
          <div class="col-md-7">
            <p class="article-content">{{ post.content|truncatechars:150|safe }} <a href="{% url "blog-detail" post.slug %}">read more</a></p>
          </div>
          <div class="col-md-5">
            <img width="100%" class="home-thumbnail" src="{{ post.thumbnail.url }}" alt="">
          </div>
        </div>
      </div>
    </article>
  {% endfor %}
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a href="?page=1" class='btn btn-outline-info'>1</a>
      <a href="?page={{page_obj.previous_page_number}}" class='btn btn-outline-info'>Previous</a>
    {% endif %}

    {% for num_page in page_obj.paginator.page_range %}
      {% if num_page == page_obj.number %}
        <a href="?page{{num_page}}" class='btn btn-info'>{{num_page}}</a>

      {% elif num_page > page_obj.number|add:'-3' and num_page < page_obj.number|add:'3' %}
        <a href="?page={{ num_page }}" class='btn btn-outline-info'>{{num_page}}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class='btn btn-outline-info'>Next</a>
      <a href='?page={{ page_obj.paginator.num_pages }}' class='btn btn-outline-info'>Last</a>
    {% endif %}
  {% endif %}
  <br><br><br>
{% endblock main %}

blogApp/templates/blogApp/search_results.html
{% extends 'blogApp/base.html' %} 
{% load search_feature %}
{% block main %} 
<h1 class="heading-3 border-bottom pb-2 mb-2">Search Blogs for "{{query}}":</h1>
  {% for post in queryset %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <img class='article-svg rounded-circle mr-2' src="{{ post.author.profile.image.url }}" alt="">
          <a class="mr-2" href="{% url 'users-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">
            {% if post.updated_at == post.created_at %}
                <i class="fas fa-plus-square"></i> Posted {{ post.created_at|timesince }} ago
            {% else %} 
              <i class="fas fa-edit mx-1"></i> Updated {{ post.updated_at|timesince }} ago
            {% endif %}           
            <i class="fas fa-eye"></i> {{ post.view_counts }}
          </small>
        </div>
        <h2><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title|highlight_search:query }}</a></h2>
        <div class="row">
          <div class="col-md-7">
            <p class="article-content">{{ post.content|highlight_search:query|truncatechars:150|safe }} <a href="{% url "blog-detail" post.slug %}">read more</a></p>
          </div>
          <div class="col-md-5">
            <img width="100%" class="home-thumbnail" src="{{ post.thumbnail.url }}" alt="">
          </div>
        </div>
      </div>
    </article>
  {% endfor %}
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a href="?page=1" class='btn btn-outline-info'>1</a>
      <a href="?page={{page_obj.previous_page_number}}" class='btn btn-outline-info'>Previous</a>
    {% endif %}

    {% for num_page in page_obj.paginator.page_range %}
      {% if num_page == page_obj.number %}
        <a href="?page{{num_page}}" class='btn btn-info'>{{num_page}}</a>

      {% elif num_page > page_obj.number|add:'-3' and num_page < page_obj.number|add:'3' %}
        <a href="?page={{ num_page }}" class='btn btn-outline-info'>{{num_page}}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class='btn btn-outline-info'>Next</a>
      <a href='?page={{ page_obj.paginator.num_pages }}' class='btn btn-outline-info'>Last</a>
    {% endif %}
  {% endif %}
  <br><br><br>
{% endblock main %}

blogApp/templates/blogApp/update.html
{% extends 'blogApp/base.html' %}
{% load crispy_forms_tags %}

{% block main %}

    <div class="content-section">
        <h2 class='border-bottom pb-3 mb-3 text-success'>Update "{{ object.title }}"</h2>
        <form action="." method='POST'>
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-success">Update</button>
        </form>
    </div>

{% endblock %}

blogApp/templates/blogApp/users_posts.html
{% extends 'blogApp/base.html' %} 
{% block main %} 
  <div class="alert alert-info">
    <h2>Posts by <strong>{{ view.kwargs.username }}</strong> <br>  Total: {{ page_obj.paginator.count }}</h2>
  </div>
  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <img class='article-svg rounded-circle' src="{{ post.author.profile.image.url }}" alt="">
          <a class="mr-2" href="#">{{ post.author }}</a>
          <small class="text-muted">
            {% if post.updated_at == post.created_at %}
              Posted {{ post.created_at|timesince }} ago
            {% else %} 
              Updated {{ post.updated_at|timesince }} ago
            {% endif %}           
          </small>
        </div>
        <h2><a class="article-title" href="{% url 'blog-detail' post.pk %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content|truncatechars:150 }} <a href="{% url "blog-detail" post.pk %}">read more</a> </p>
      </div>
    </article>
  {% endfor %} 
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a href="?page=1" class="btn btn-outline-success">1</a>
      <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-success">Previous</a>
    {% endif %}

    {% for page_num in page_obj.paginator.page_range %}
      {% if page_num == page_obj.number %}
            <a href="?page={{ page_num }}" class="btn btn-success">{{ page_num }}</a>
      {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
            <a href="?page={{ page_num }}" class="btn btn-outline-success">{{ page_num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-success">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-success">Last</a>
    {% endif %}
  {% endif %}
  <br><br><br>
{% endblock main %}